spring:
  application:
    name: Spring-craft
  threads:
    virtual:
      enabled: true
  mvc:
    apiversion:
      default: 1
      use:
        path-segment: 1
      supported: 1.0,2.0
product-url: https://api.restful-api.dev

